name: todo_riverpod
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  
  flutter_screenutil: ^5.8.4
  google_fonts: ^5.0.0
  hooks_riverpod: ^2.3.6
  ionicons: ^0.2.2
  smooth_page_indicator: ^1.1.0
  country_picker: ^2.0.20
  pinput: ^2.2.31
  flutter_vector_icons: ^2.0.0
  riverpod_annotation: ^2.1.1

  sqflite: ^2.2.8+4
  dynamic_color: ^1.6.6
  flutter_datetime_picker_plus: ^2.0.1
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  flutter_local_notifications: ^15.1.0+1
  rxdart: ^0.27.7
  timezone: ^0.9.2
  flutter_bloc: ^8.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
