// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP0ClC_8fE_43wmfyB-Lwk1fR40CARvHQ',
    appId: '1:577385645240:web:9516ed68cbbce466fb204d',
    messagingSenderId: '577385645240',
    projectId: 'todo-riverpod-1e1d1',
    authDomain: 'todo-riverpod-1e1d1.firebaseapp.com',
    storageBucket: 'todo-riverpod-1e1d1.appspot.com',
    measurementId: 'G-QN21SJQ7KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQFhK3_J7EcXuGPNXDYLtJKRh_M7bUhXA',
    appId: '1:577385645240:android:6f944cd9313a8513fb204d',
    messagingSenderId: '577385645240',
    projectId: 'todo-riverpod-1e1d1',
    storageBucket: 'todo-riverpod-1e1d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXDw-2_8ZtBVAHzrqpVaJ0AyfMh5pw37o',
    appId: '1:577385645240:ios:23e86bbeaeb6bd88fb204d',
    messagingSenderId: '577385645240',
    projectId: 'todo-riverpod-1e1d1',
    storageBucket: 'todo-riverpod-1e1d1.appspot.com',
    androidClientId: '577385645240-l117kl2qspc8sfl6gtd9qqn9gj3p7iru.apps.googleusercontent.com',
    iosClientId: '577385645240-m7bhbhvbvnuqed9jqsjfjlgmit0vjsob.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXDw-2_8ZtBVAHzrqpVaJ0AyfMh5pw37o',
    appId: '1:577385645240:ios:e4a2b334d9c7822bfb204d',
    messagingSenderId: '577385645240',
    projectId: 'todo-riverpod-1e1d1',
    storageBucket: 'todo-riverpod-1e1d1.appspot.com',
    androidClientId: '577385645240-l117kl2qspc8sfl6gtd9qqn9gj3p7iru.apps.googleusercontent.com',
    iosClientId: '577385645240-v0u1qfjcrg2tvov46hrl3q74iaogehgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoRiverpod.RunnerTests',
  );
}
